<x-app-layout>
    @section('content')
        <x-conversation-list/>
        <x-conversation-list/>
        <x-conversation-list/>
        <x-conversation-list/>
        <x-conversation-list/>
    @endsection
</x-app-layout>